### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by jhorlima** [guyaristide/youtuyer#1]
How to install?

**Comment by agnamc9** [comment]
Actually like this

```yml
youtuyer:
    git:
      url: git://github.com/guyaristide/youtuyer.git
```
